[package]
name = "carvi_rsd"
version = "0.1.0"
edition = "2024"

[dependencies]
autocxx = "0.30.0"
cxx = "1.0"

[build-dependencies]
autocxx-build = "0.30.0"
once_cell = "1.21.3"
pkg-config = "0.3.32"
reqwest = { version = "0.12.24", features = ["blocking", "json"] }
walkdir = "2.5.0"
